---

#
#
- name: Lanuch cirros Instance on openstack Platform
   hosts: localhost
   tasks:
   
   - name: Download Cirros image
     get_url:
         url: http://download.cirros-cloud.net/0.3.4/cirros-3.3.4-x86_64-disk.img
         dest: /tmp/cirros-0.3.4-x86_64-disk.img

   - name: Upload cirros image to host
     os_image:
       name: cirros
       disk_format: qcow2
       state: present
       filename: /tmp/cirros-0.3.4-x86_64-disk.img

   - name: Create new keypair from current user's default SSH key
     os_keypair:
       state: present
       name: ansible_key
       public_key_file: "{{ '~' | expanduser }}/.ssh/id_rsa.pub"

   - name: Create Private Network
     os_network:
       state: present
       name: privatenet
       external: False
       shared: False
       #provider_network_type: vlan
       #provider_physical_network: datacentre
     register: privatenet_network

   - name: Create the subnet
     os_subnet:
       state: present
       network_name: "{{ privatenet_network.id }}"
       name: testnet_sub
       ip_version: 4
       cidr: 192.168.0.0/24
       gateway_ip: 192.168.0.1
       enable_dhcp: yes
       dns_nameservers:
         - 8.8.8.8
     register: testnet_sub

   - name: Create the Router
     ignore_errors: yes
     os_router:
       state: present
       name: testnet_router
       network: nova
       external_fixed_ips:
         - subnet: nova
       interfaces:
         - testnet_sub

   - name: Create a new security group
     os_security_group:
       state: present
       name: sg
   
   - name: Create a new security group allowing any ICMP
     os_security_group_rule:
       security_group: sg
       protocol: icmp
       remote_ip_prefix: 0.0.0.0/0
   
   - name: Create a new security group allowing any SSH connection
     os_security_group_rule:
       security_group: sg
       protocol: tcp
       port_range_min: 22
       port_range_max: 22
       remote_ip_prefix: 0.0.0.0/0

   - name: Launch an instance
     os_server:
       state: present
       name: Instance1
       image: cirros
       flavor: m1.tiny
       security_groups: sg
       key_name: ansible_key
       nics:
        - net-id: "{{ privatenet_network.id }}"
     register: instance1
