---

   - name: Create a new security group
     os_security_group:
       state: present
       name: sg
   
   - name: Create a new security group allowing any ICMP
     os_security_group_rule:
       security_group: sg
       protocol: icmp
       remote_ip_prefix: 0.0.0.0/0
   
   - name: Create a new security group allowing any SSH connection
     os_security_group_rule:
       security_group: sg
       protocol: tcp
       port_range_min: 22
       port_range_max: 22
       remote_ip_prefix: 0.0.0.0/0
